Update 03_point_method.py
если не затруднит подскажите что не так в коде, все передается, в метод класса правильно, а VScode возвращает
TypeError: Point.dist_to() missing 1 required positional argument: 'other_point'